# Generated by Django 3.0.6 on 2020-05-10 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('user_id', models.IntegerField(default=0, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_companies.Company')),
            ],
        ),
    ]
