# Generated by Django 3.0.6 on 2020-05-10 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_companies', '0001_initial'),
        ('app_licences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_companies.Company'),
        ),
    ]
